name: cat_app
description: "A new Flutter project for displaying Cats' images"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  http: ^1.2.0
  cupertino_icons: ^1.0.2
  toast: ^0.3.0
  flutter_staggered_grid_view: ^0.6.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
